export const FontFamily = {
  poppins_black: "Poppins-Black",
  poppins_black_italic: "Poppins-BlackItalic",
  poppins_bold: "Poppins-Bold",
  poppins_bold_italic: "Poppins-BoldItalic",
  poppins_extra_bold: "Poppins-ExtraBold",
  poppins_extraBoldItalic: "Poppins-ExtraBoldItalic",
  poppins_extra_light: "Poppins-ExtraLight",
  poppins_extral_italic: "Poppins-ExtraLightItalic",
  poppins_italic: "Poppins-Italic",
  poppins_light: "Poppins-light",
  poppins_light_italic: "Poppins-LightItalic",
  poppins_medium: "Poppins-Medium",
  poppins_regular_italic: "Poppins-MediumItalic",
  poppins_regular: "Poppins-Regular",
  poppins_semibold: "Poppins-SemiBold",
  poppins_semibold_italic: "Poppins-SemiBoldItalic",
  poppins_thin: "Poppins-Thin",
  poppins_thin_italic: "Poppins-ThinItalic",
};
