import { NativeStackScreenProps as RNStackScreenProps } from "@react-navigation/native-stack";
export enum APP_SCREEN {
  SPLASH = "SPLASH",
  ONBOARDING_SCREEN = "ONBOARDING_SCREEN",
  INPUT_PASSWORD_SCREEN = "INPUT_PASSWORD_SCREEN",
  CREATE_PASSWORD_SCREEN = "CREATE_PASSWORD_SCREEN",
  CONFIRM_PASSWORD_SCREEN = "CONFIRM_PASSWORD_SCREEN",
  LOGIN_SCREEN = "LOGIN_SCREEN",
  REGISTER_SCREEN = "REGISTER_SCREEN",
  INPUT_NUMBER_SCREEN = "INPUT_NUMBER_SCREEN",
  VERIFY_NUMBER_SCREEN = "VERIFY_NUMBER_SCREEN",
  SELECT_ACCOUNT_TYPE_SCREEN = "SELECT_ACCOUNT_TYPE_SCREEN",
  MAIN_TAB = "MAIN_TAB",
  HOME_SCREEN = "HOME_SCREEN",
  CALENDA_SCREEN = "CALENDA_SCREEN",
  RESULT_SCREEN = "RESULT_SCREEN",
  PAYMENT_SCREEN = "PAYMENT_SCREEN",
  ACCOUNT_SCREEN = "ACCOUNT_SCREEN",
  SEARCH_SCREEN = "SEARCH_SCREEN",
  TUTOR_DETAIL_SCREEN = "TUTOR_DETAIL_SCREEN",
  BOOKING_SCREEN = "BOOKING_SCREEN",
  PAYMENT_DETAIL_SCREEN = "PAYMENT_DETAIL_SCREEN",
  PAYMENT_GUIDE_SCREEN = "PAYMENT_GUIDE_SCREEN",
  CALENDA_PARENT_DETAIL_SCREEN = "CALENDA_PARENT_DETAIL_SCREEN",
  BOOKING_INFOR_TUTOR_SCREEN = "BOOKING_INFOR_TUTOR_SCREEN",
  BOOKING_INFOR_PARENT_SCREEN = "BOOKING_INFOR_PARENT_SCREEN",
  REGISTER_INFOR_TUTOR_SCREEN = "REGISTER_INFOR_TUTOR_SCREEN",
  REGISTER_INFOR_PARENT_SCREEN = "REGISTER_INFOR_PARENT_SCREEN",
  RESULT_LATEST_SCREEN = "RESULT_LATEST_SCREEN",
  LEARNING_OUTCOMES_SCREEN = "LEARNING_OUTCOMES_SCREEN",
  TEACHING_SCREEN = "TEACHING_SCREEN",
  CLASS_DETAIL_SCREEN = "CLASS_DETAIL_SCREEN",
  HUSBAND_WIFE_ACCOUNT_SCREEN = "HUSBAND_WIFE_ACCOUNT_SCREEN",
  CHILDREN_ACCOUNT_SCREEN = "CHILDREN_ACCOUNT_SCREEN",
  ADD_NEW_CALENDAR_SCREEN = "ADD_NEW_CALENDAR_SCREEN",
  DETAIL_CALENDAR_TUTOR_SCREEN = "DETAIL_CALENDAR_TUTOR_SCREEN",
  DETAIL_CALENDAR_PARENT_SCREEN = "DETAIL_CALENDAR_PARENT_SCREEN",
  ACCOUNT_PARENT_DETAILS_SCREEN = "ACCOUNT_PARENT_DETAILS_SCREEN",
  ACCOUNT_TUTOR_DETAILS_SCREEN = "ACCOUNT_TUTOR_DETAILS_SCREEN",
  OUTSTANDING_TUTOR_SCREEN = "OUTSTANDING_TUTOR_SCREEN",
  NOTIFICATION_SCREEN = "NOTIFICATION_SCREEN",
  INFOR_APPLICATION_SCREEN = "INFOR_APPLICATION_SCREEN",
  CREATE_RESULT_LEARNING = "CREATE_RESULT_LEARNING",
  FEED_BACK_SCREEN = "FEED_BACK_SCREEN",
}

export type StackParamsList = {
  [APP_SCREEN.SPLASH]: undefined;
  [APP_SCREEN.ONBOARDING_SCREEN]: undefined;
  [APP_SCREEN.LOGIN_SCREEN]: undefined;
  [APP_SCREEN.INPUT_PASSWORD_SCREEN]: RouteInputPassword;
  [APP_SCREEN.CREATE_PASSWORD_SCREEN]: RouteCreatePassword;
  [APP_SCREEN.CONFIRM_PASSWORD_SCREEN]: RouteConfirmPassword;
  [APP_SCREEN.REGISTER_SCREEN]: undefined;
  [APP_SCREEN.INPUT_NUMBER_SCREEN]: RouteInputPassword;
  [APP_SCREEN.VERIFY_NUMBER_SCREEN]: RouteVerify;
  [APP_SCREEN.SELECT_ACCOUNT_TYPE_SCREEN]: RouteSelectAccountType;
  [APP_SCREEN.MAIN_TAB]: undefined;
  [APP_SCREEN.HOME_SCREEN]: undefined;
  [APP_SCREEN.CALENDA_SCREEN]: undefined;
  [APP_SCREEN.RESULT_SCREEN]: undefined;
  [APP_SCREEN.PAYMENT_SCREEN]: undefined;
  [APP_SCREEN.ACCOUNT_SCREEN]: undefined;
  [APP_SCREEN.SEARCH_SCREEN]: SearchTutorParams;
  [APP_SCREEN.TUTOR_DETAIL_SCREEN]: TutorDetailInteface;
  [APP_SCREEN.BOOKING_SCREEN]: BookingInforRouter;
  [APP_SCREEN.PAYMENT_DETAIL_SCREEN]: PaymentDetailRouters;
  [APP_SCREEN.PAYMENT_GUIDE_SCREEN]: undefined;
  [APP_SCREEN.CALENDA_PARENT_DETAIL_SCREEN]: RouteCalendaParentDetails;
  [APP_SCREEN.BOOKING_INFOR_TUTOR_SCREEN]: BookingDetailInterface;
  [APP_SCREEN.BOOKING_INFOR_PARENT_SCREEN]: BookingDetailInterface;
  [APP_SCREEN.REGISTER_INFOR_TUTOR_SCREEN]: undefined;
  [APP_SCREEN.REGISTER_INFOR_PARENT_SCREEN]: undefined;
  [APP_SCREEN.RESULT_LATEST_SCREEN]: RouteResultsLatest;
  [APP_SCREEN.LEARNING_OUTCOMES_SCREEN]: RouteResultsDetail;
  [APP_SCREEN.TEACHING_SCREEN]: RouteTeachingClass;
  [APP_SCREEN.CLASS_DETAIL_SCREEN]: undefined;
  [APP_SCREEN.HUSBAND_WIFE_ACCOUNT_SCREEN]: undefined;
  [APP_SCREEN.CHILDREN_ACCOUNT_SCREEN]: undefined;
  [APP_SCREEN.ADD_NEW_CALENDAR_SCREEN]: undefined;
  [APP_SCREEN.DETAIL_CALENDAR_TUTOR_SCREEN]: EventRoute;
  [APP_SCREEN.DETAIL_CALENDAR_PARENT_SCREEN]: EventRoute;
  [APP_SCREEN.ACCOUNT_PARENT_DETAILS_SCREEN]: undefined;
  [APP_SCREEN.ACCOUNT_TUTOR_DETAILS_SCREEN]: undefined;
  [APP_SCREEN.OUTSTANDING_TUTOR_SCREEN]: undefined;
  [APP_SCREEN.NOTIFICATION_SCREEN]: undefined;
  [APP_SCREEN.INFOR_APPLICATION_SCREEN]: undefined;
  [APP_SCREEN.CREATE_RESULT_LEARNING]: ResultLearningRoute;
  [APP_SCREEN.FEED_BACK_SCREEN]: FeedBackParams;
};
export type RootNativeStackParamList = StackParamsList;

export type StackScreenProps<T extends keyof StackParamsList> =
  RNStackScreenProps<StackParamsList, T>;
